export const PROBLEM_IDS = [
  "stack",
  "queue",
  "hash-map",
  "deque",
  "linked-list",
  "min-heap",
  "binary-search",
  "merge-sort",
  "bfs",
  "dfs",
  "union-find",
  "basic-dp",
  "array-string",
  "prefix-sum",
  "two-pointers",
  "sliding-window",
  "recursion-backtracking",
  "greedy",
  "binary-tree",
  "binary-search-tree",
  "dijkstra",
  "topological-sort",
  "knapsack-dp",
] as const;

export type ProblemId = (typeof PROBLEM_IDS)[number];
