import type { ReferenceSolutionSet } from "../types.ts";

const scanner = String.raw`static final class FastScanner {
    private final InputStream in = System.in; private final byte[] buffer = new byte[1 << 16]; private int ptr, len;
    private int read() throws IOException { if (ptr >= len) { len = in.read(buffer); ptr = 0; if (len < 0) return -1; } return buffer[ptr++]; }
    long nextLong() throws IOException { int c, sign = 1; long value = 0; do c = read(); while (c <= 32 && c >= 0); if (c == '-') { sign = -1; c = read(); } while (c > 32) { value = value * 10 + c - '0'; c = read(); } return value * sign; }
    int nextInt() throws IOException { return (int) nextLong(); }
    String next() throws IOException { int c; StringBuilder value = new StringBuilder(); do c = read(); while (c <= 32 && c >= 0); while (c > 32) { value.append((char)c); c = read(); } return value.toString(); }
}`;
const java = (body: string) => String.raw`import java.io.*;
import java.util.*;
public class Main {
${scanner}
${body}
}`;

export const expandedJavaSolutions = {
  "array-string": java(String.raw`public static void main(String[] args) throws Exception { FastScanner fs=new FastScanner(); String s=fs.next(); StringBuilder out=new StringBuilder(); int start=0; for(int i=1;i<=s.length();i++) if(i==s.length()||s.charAt(i)!=s.charAt(start)){out.append(s.charAt(start)).append(' ').append(i-start).append('\n');start=i;} System.out.print(out); }`),
  "prefix-sum": java(String.raw`public static void main(String[] args) throws Exception { FastScanner fs=new FastScanner(); int n=fs.nextInt(),q=fs.nextInt(); long[] p=new long[n+1]; for(int i=1;i<=n;i++)p[i]=p[i-1]+fs.nextLong(); StringBuilder out=new StringBuilder(); while(q-->0){int l=fs.nextInt(),r=fs.nextInt();out.append(p[r]-p[l-1]).append('\n');}System.out.print(out); }`),
  "two-pointers": java(String.raw`public static void main(String[] args) throws Exception { FastScanner fs=new FastScanner(); int n=fs.nextInt();long target=fs.nextLong();long[]a=new long[n];for(int i=0;i<n;i++)a[i]=fs.nextLong();int l=0,r=n-1;while(l<r){long sum=a[l]+a[r];if(sum==target){System.out.print("YES");return;}if(sum<target)l++;else r--;}System.out.print("NO"); }`),
  "sliding-window": java(String.raw`public static void main(String[] args) throws Exception { FastScanner fs=new FastScanner();int n=fs.nextInt(),k=fs.nextInt();String s=fs.next();int[]count=new int[26];int left=0,kinds=0,answer=0;for(int right=0;right<n;right++){int x=s.charAt(right)-'a';if(count[x]++==0)kinds++;while(kinds>k){int y=s.charAt(left++)-'a';if(--count[y]==0)kinds--;}answer=Math.max(answer,right-left+1);}System.out.print(answer); }`),
  "recursion-backtracking": java(String.raw`static int n,r;static int[] values,path;static boolean[] used;static StringBuilder out=new StringBuilder();
static void search(int depth){if(depth==r){for(int i=0;i<r;i++){if(i>0)out.append(' ');out.append(path[i]);}out.append('\n');return;}for(int i=0;i<n;i++)if(!used[i]){used[i]=true;path[depth]=values[i];search(depth+1);used[i]=false;}}
public static void main(String[] args) throws Exception {FastScanner fs=new FastScanner();n=fs.nextInt();r=fs.nextInt();values=new int[n];path=new int[r];used=new boolean[n];for(int i=0;i<n;i++)values[i]=fs.nextInt();Arrays.sort(values);search(0);System.out.print(out);}`),
  greedy: java(String.raw`public static void main(String[] args) throws Exception {FastScanner fs=new FastScanner();long amount=fs.nextLong(),answer=0;for(int coin:new int[]{500,100,50,10,5,1}){answer+=amount/coin;amount%=coin;}System.out.print(answer);}`),
  "binary-tree": java(String.raw`public static void main(String[] args) throws Exception {FastScanner fs=new FastScanner();int n=fs.nextInt();int[][]child=new int[n+1][2];for(int i=1;i<=n;i++){child[i][0]=fs.nextInt();child[i][1]=fs.nextInt();}ArrayDeque<Integer>q=new ArrayDeque<>();q.add(1);int height=0;while(!q.isEmpty()){height++;for(int size=q.size();size>0;size--){int u=q.remove();if(child[u][0]!=0)q.add(child[u][0]);if(child[u][1]!=0)q.add(child[u][1]);}}System.out.print(height);}`),
  "binary-search-tree": java(String.raw`static final class Node{long key;int left,right;Node(long k,int l,int r){key=k;left=l;right=r;}}static final class State{int node;long low,high;State(int n,long l,long h){node=n;low=l;high=h;}}
public static void main(String[] args) throws Exception {FastScanner fs=new FastScanner();int n=fs.nextInt();Node[]a=new Node[n+1];for(int i=1;i<=n;i++)a[i]=new Node(fs.nextLong(),fs.nextInt(),fs.nextInt());ArrayDeque<State>stack=new ArrayDeque<>();stack.push(new State(1,Long.MIN_VALUE,Long.MAX_VALUE));while(!stack.isEmpty()){State s=stack.pop();Node x=a[s.node];if(x.key<=s.low||x.key>=s.high){System.out.print("NO");return;}if(x.left!=0)stack.push(new State(x.left,s.low,x.key));if(x.right!=0)stack.push(new State(x.right,x.key,s.high));}System.out.print("YES");}`),
  dijkstra: java(String.raw`static final class Edge{int to,w;Edge(int t,int w){to=t;this.w=w;}}static final class Item implements Comparable<Item>{long cost;int node;Item(long c,int n){cost=c;node=n;}public int compareTo(Item other){return Long.compare(cost,other.cost);}}
public static void main(String[] args) throws Exception {FastScanner fs=new FastScanner();int n=fs.nextInt(),m=fs.nextInt(),start=fs.nextInt();List<Edge>[]g=new ArrayList[n+1];for(int i=1;i<=n;i++)g[i]=new ArrayList<>();while(m-->0){int u=fs.nextInt();g[u].add(new Edge(fs.nextInt(),fs.nextInt()));}long inf=Long.MAX_VALUE/4;long[]d=new long[n+1];Arrays.fill(d,inf);PriorityQueue<Item>q=new PriorityQueue<>();d[start]=0;q.add(new Item(0,start));while(!q.isEmpty()){Item current=q.remove();if(current.cost!=d[current.node])continue;for(Edge e:g[current.node]){long next=current.cost+e.w;if(next<d[e.to]){d[e.to]=next;q.add(new Item(next,e.to));}}}StringBuilder out=new StringBuilder();for(int i=1;i<=n;i++){if(i>1)out.append(' ');out.append(d[i]==inf?"INF":Long.toString(d[i]));}System.out.print(out);}`),
  "topological-sort": java(String.raw`public static void main(String[] args) throws Exception {FastScanner fs=new FastScanner();int n=fs.nextInt(),m=fs.nextInt();List<Integer>[]g=new ArrayList[n+1];int[]deg=new int[n+1];for(int i=1;i<=n;i++)g[i]=new ArrayList<>();while(m-->0){int a=fs.nextInt(),b=fs.nextInt();g[a].add(b);deg[b]++;}PriorityQueue<Integer>q=new PriorityQueue<>();for(int i=1;i<=n;i++)if(deg[i]==0)q.add(i);StringBuilder out=new StringBuilder();while(!q.isEmpty()){int u=q.remove();if(out.length()>0)out.append(' ');out.append(u);for(int v:g[u])if(--deg[v]==0)q.add(v);}System.out.print(out);}`),
  "knapsack-dp": java(String.raw`public static void main(String[] args) throws Exception {FastScanner fs=new FastScanner();int n=fs.nextInt(),capacity=fs.nextInt();long[]dp=new long[capacity+1];while(n-->0){int weight=fs.nextInt();long value=fs.nextLong();for(int c=capacity;c>=weight;c--)dp[c]=Math.max(dp[c],dp[c-weight]+value);}System.out.print(dp[capacity]);}`),
} satisfies Partial<ReferenceSolutionSet>;
